@baseUrl = https://localhost:7125/api/menuitems
@contentType = application/json

### Login and Get JWT Token
# This request logs in and retrieves the JWT token for authentication.
POST {{baseUrl}}/auth/login
Content-Type: @contentType

{
    "email": "agile_admin@actors.com",
    "password": "1234567890"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### ✅ Get All MenuItems
GET {{baseUrl}}

### ✅ Get a Menu Item by ID
GET {{baseUrl}}/1

### ✅ Create a New Menu Item
POST {{baseUrl}}
Content-Type: {{contentType}}

{
    {
    "name": "Veggie Burger",
    "ingredients": "Veggie Patty, Lettuce, Tomato, Whole Wheat Bun",
    "allergies": "Gluten",
    "price": 9.99,
    "expectedPrepMinutes": 12
    }
}

### ✅ Update an Existing Menu Item
PUT {{baseUrl}}/1
Content-Type: {{contentType}}

{
    "name": "Vegan Burger",
    "ingredients": "Plant-based Patty, Lettuce, Tomato, Gluten-Free Bun",
    "allergies": "None",
    "price": 10.99,
    "expectedPrepMinutes": 12
}

### ✅ Delete a Menu Item by ID
DELETE {{baseUrl}}/1

###
